// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHMp_iE9F8gCTmbEoyFk2eJj5Zlgg_kcI',
    appId: '1:962655758326:web:8d676f947ec420f3fc09d7',
    messagingSenderId: '962655758326',
    projectId: 'chatapptute-e5d2c',
    authDomain: 'chatapptute-e5d2c.firebaseapp.com',
    storageBucket: 'chatapptute-e5d2c.appspot.com',
    measurementId: 'G-D53XD5B9J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXADBNNsr_6cuypIdiMJMc60S1BSPzOHM',
    appId: '1:962655758326:android:536b9be3e54fcb88fc09d7',
    messagingSenderId: '962655758326',
    projectId: 'chatapptute-e5d2c',
    storageBucket: 'chatapptute-e5d2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHOtTgscvyDn8Ee-hJx8h4daBBMkyGtwk',
    appId: '1:962655758326:ios:749b9adb7fafe664fc09d7',
    messagingSenderId: '962655758326',
    projectId: 'chatapptute-e5d2c',
    storageBucket: 'chatapptute-e5d2c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHOtTgscvyDn8Ee-hJx8h4daBBMkyGtwk',
    appId: '1:962655758326:ios:749b9adb7fafe664fc09d7',
    messagingSenderId: '962655758326',
    projectId: 'chatapptute-e5d2c',
    storageBucket: 'chatapptute-e5d2c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHMp_iE9F8gCTmbEoyFk2eJj5Zlgg_kcI',
    appId: '1:962655758326:web:d979c656d5a68975fc09d7',
    messagingSenderId: '962655758326',
    projectId: 'chatapptute-e5d2c',
    authDomain: 'chatapptute-e5d2c.firebaseapp.com',
    storageBucket: 'chatapptute-e5d2c.appspot.com',
    measurementId: 'G-Z7FBDVP99B',
  );
}
